#
# DigitalOcean App Platform Specification - Full Stack
# Frontend on survivalindex.org, Backend API on api.survivalindex.org
# Deploy with: doctl apps update 6affe60f-7a82-4713-9f9a-9d5936b3762c --spec .do/app.yaml
#

name: survivalindex
region: nyc

# Backend API Service
services:
  - name: backend
    github:
      repo: selwyntheo/survivalindex
      branch: main
      deploy_on_push: true

    source_dir: /apps/backend

    build_command: npm install && npx prisma generate && npx prisma migrate deploy
    run_command: npm start

    http_port: 8080

    instance_count: 1
    instance_size_slug: basic-xxs

    envs:
      - key: NODE_ENV
        scope: RUN_TIME
        value: "production"
      - key: PORT
        scope: RUN_TIME
        value: "8080"
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: FRONTEND_URL
        scope: RUN_TIME
        value: "https://survivalindex.org"
      - key: ANTHROPIC_API_KEY
        scope: RUN_TIME
        type: SECRET

    health_check:
      http_path: /api/health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

# Frontend Static Site
static_sites:
  - name: frontend
    github:
      repo: selwyntheo/survivalindex
      branch: main
      deploy_on_push: true

    source_dir: /apps/frontend

    build_command: npm install && npm run build
    output_dir: dist

    envs:
      - key: VITE_API_URL
        scope: BUILD_TIME
        value: "https://api.survivalindex.org"

    routes:
      - path: /

    catchall_document: index.html

# Custom domains
domains:
  - domain: survivalindex.org
    type: PRIMARY
    zone: survivalindex.org
  - domain: api.survivalindex.org
    type: ALIAS
    zone: survivalindex.org
