#
# DigitalOcean App Platform Specification
# Deploy SurvivalIndex with: doctl apps create --spec .do/app.yaml
#

name: survivalindex
region: nyc

# Backend API Service
services:
  - name: backend
    github:
      repo: selwyntheo/survivalindex
      branch: main
      deploy_on_push: true

    source_dir: /backend

    build_command: npm install
    run_command: npm start

    envs:
      - key: NODE_ENV
        scope: RUN_TIME
        value: production

      - key: PORT
        scope: RUN_TIME
        value: "8080"

    http_port: 8080

    health_check:
      http_path: /health
      initial_delay_seconds: 20
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

    instance_count: 1
    instance_size_slug: basic-xxs  # 512MB RAM, $5/month

    routes:
      - path: /api
      - path: /health

# Frontend Static Site
static_sites:
  - name: frontend
    github:
      repo: selwyntheo/survivalindex
      branch: main
      deploy_on_push: true

    source_dir: /

    build_command: npm install && npm run build
    output_dir: dist

    envs:
      - key: VITE_API_URL
        scope: BUILD_TIME
        value: ${backend.PUBLIC_URL}

    routes:
      - path: /

    catchall_document: index.html
