#
# DigitalOcean App Platform Specification - Frontend Only
# Backend is deployed separately via Docker on a Droplet
# Deploy with: doctl apps update 6affe60f-7a82-4713-9f9a-9d5936b3762c --spec .do/app.yaml
#

name: survivalindex
region: nyc

# Frontend Static Site
static_sites:
  - name: frontend
    github:
      repo: selwyntheo/survivalindex
      branch: main
      deploy_on_push: true

    source_dir: /apps/frontend

    build_command: npm install && npm run build
    output_dir: dist

    envs:
      - key: VITE_API_URL
        scope: BUILD_TIME
        value: "https://api.survivalindex.org"

    routes:
      - path: /

    catchall_document: index.html
